import { existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const PKG = "@eve-studio/extension";
const GENERATED_MOUNT = `export { default } from "${PKG}";\n`;

export type MountResult =
  | { kind: "ready"; command: string[]; mountFile: string; created: boolean }
  | { kind: "conflict"; command: string[]; mountFile: string };

export function createdMountFile(result: MountResult): string | undefined {
  return result.kind === "ready" && result.created ? result.mountFile : undefined;
}

/** Removes only the untouched regular file generated by scaffoldMount. */
export function removeGeneratedMountFile(mountFile: string): boolean {
  try {
    if (!lstatSync(mountFile).isFile()) return false;
    if (readFileSync(mountFile, "utf8") !== GENERATED_MOUNT) return false;
    unlinkSync(mountFile);
    return true;
  } catch {
    return false;
  }
}

export function isExtensionMounted(projectRoot: string): boolean {
  try {
    const pkg = JSON.parse(readFileSync(join(projectRoot, "package.json"), "utf8"));
    const hasDep = Boolean(pkg.dependencies?.[PKG] ?? pkg.devDependencies?.[PKG]);
    if (!hasDep) return false;
    const extDir = join(projectRoot, "agent", "extensions");
    if (!existsSync(extDir)) return false;
    return readdirSync(extDir).some((f) => f.endsWith(".ts") && readFileSync(join(extDir, f), "utf8").includes(PKG));
  } catch {
    return false;
  }
}

export function detectPackageManager(projectRoot: string): "pnpm" | "yarn" | "bun" | "npm" {
  let dir = projectRoot;
  for (let i = 0; i < 6; i++) {
    if (existsSync(join(dir, "pnpm-lock.yaml"))) return "pnpm";
    if (existsSync(join(dir, "yarn.lock"))) return "yarn";
    if (existsSync(join(dir, "bun.lockb")) || existsSync(join(dir, "bun.lock"))) return "bun";
    if (existsSync(join(dir, "package-lock.json"))) return "npm";
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return "npm";
}

export function scaffoldMount(projectRoot: string): MountResult {
  const pm = detectPackageManager(projectRoot);
  const command = pm === "npm" ? ["npm", "install", PKG] : [pm, "add", PKG];
  const mountFile = join(projectRoot, "agent", "extensions", "studio.ts");
  mkdirSync(dirname(mountFile), { recursive: true });
  try {
    writeFileSync(mountFile, GENERATED_MOUNT, { flag: "wx" });
    return { kind: "ready", command, mountFile, created: true };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
    if (readFileSync(mountFile, "utf8") === GENERATED_MOUNT) {
      return { kind: "ready", command, mountFile, created: false };
    }
    return { kind: "conflict", command, mountFile };
  }
}

export function mountInstructions(projectRoot: string): string {
  const pm = detectPackageManager(projectRoot);
  const add = pm === "npm" ? "npm install" : `${pm} add`;
  return [
    `To capture live events, mount the Studio extension in ${projectRoot}:`,
    `  1. ${add} ${PKG}`,
    `  2. create agent/extensions/studio.ts containing:  export { default } from "${PKG}";`,
    `Sessions started before mounting are only visible via --scan-disk.`,
  ].join("\n");
}
